spring.application.name=cqrs_query
server.port=8622

# Configuración de Mongo
#spring.data.mongodb.uri=mongodb://user_query:123456@localhost:27017/bd_query

# o, si no usas credenciales:
spring.data.mongodb.uri=mongodb://localhost:27017/query_db

# Log, lo puedes dejar igual si te funciona
spring.logging.path=./logs
spring.logging.max.size=10 MB
